[package]
name = "grove-management-service"
version.workspace = true
edition.workspace = true

[dependencies]
filegate-db.workspace = true
filegate-core.workspace = true
grove-management-policy.workspace = true
grove-management-command.workspace = true
uuid.workspace = true
tokio.workspace = true
tracing.workspace = true
subtle.workspace = true

[dev-dependencies]
sqlx.workspace = true
chrono.workspace = true

[lints]
workspace = true
