[package]
name = "grove-management-service"
version.workspace = true
edition.workspace = true

[dependencies]
grove-db.workspace = true
grove-core.workspace = true
grove-management-policy.workspace = true
grove-management-command.workspace = true
uuid.workspace = true
tokio.workspace = true
tracing.workspace = true
argon2.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
serde_json.workspace = true
sqlx.workspace = true
chrono.workspace = true

[lints]
workspace = true
