[package]
name = "grove-infra"
version.workspace = true
edition.workspace = true

[dependencies]
grove-storage-provider.workspace = true
anyhow = { workspace = true }
tokio = { workspace = true }
grove-object-policy = { workspace = true }

[dev-dependencies]
axum.workspace = true
secrecy.workspace = true
uuid = { workspace = true }

[lints]
workspace = true
