[package]
name = "filegate-core"
version.workspace = true
edition.workspace = true

[dependencies]
aes-gcm = { workspace = true }
dotenvy = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
md-5 = { workspace = true }
secrecy = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
