[package]
name = "filegate-db"
version.workspace = true
edition.workspace = true

[dependencies]
grove-management-policy.workspace = true
sqlx = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
