[package]
name = "grove-storage-provider"
version.workspace = true
edition.workspace = true

[dependencies]
grove-core.workspace = true
aws-smithy-async.workspace = true
aws-sdk-s3.workspace = true
aws-smithy-http-client.workspace = true
anyhow.workspace = true
tokio.workspace = true
secrecy.workspace = true

[dev-dependencies]
chrono.workspace = true
axum.workspace = true

[lints]
workspace = true
